version: "3.9"

services:
  test_runner:
    build: .
    container_name: test_runner
    command: poetry run pytest tests -v -s
    depends_on:
      - postgres_test
    environment:
      - PYTHONPATH=/app
      - DATABASE_URL=postgresql+asyncpg://test_user:test_pass@postgres_test:5432/test_db
    env_file:
      - .env
    volumes:
      - .:/app

  postgres_test:
    image: postgres:17
    container_name: postgres_test
    environment:
      POSTGRES_DB: test_db
      POSTGRES_USER: test_user
      POSTGRES_PASSWORD: test_pass
    ports:
      - "5433:5432"
