"""empty message

Revision ID: 283d4d571465
Revises: 6aa1f68a1635
Create Date: 2025-04-13 13:39:42.246798

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.sql.expression import false


# revision identifiers, used by Alembic.
revision: str = '283d4d571465'
down_revision: Union[str, None] = '6aa1f68a1635'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('articles', sa.Column('deleted', sa.Boolean(), nullable=False, server_default=false()))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('articles', 'deleted')
    # ### end Alembic commands ###
