"""empty message

Revision ID: 921767ad9245
Revises: 96e8c1c4a23f
Create Date: 2025-04-11 15:10:11.206936

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '921767ad9245'
down_revision: Union[str, None] = '96e8c1c4a23f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('articles_title_key', 'articles', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('articles_title_key', 'articles', ['title'])
    # ### end Alembic commands ###
